-- district_master_schema.sql
-- Bronze table: district_master
-- Aggregated metrics per district (demographics, labor, housing, rent, income)

CREATE TABLE `berlin-housing.bronze.district_master` (
  district STRING,
  district_not_working_percentage FLOAT64,
  district_labor_force FLOAT64,
  district_male_labor_force FLOAT64,
  district_female_labor_force FLOAT64,
  district_total_households FLOAT64,
  district_single_households FLOAT64,
  district_couples_without_children FLOAT64,
  district_couples_without_children_percentage FLOAT64,
  district_couples_with_children FLOAT64,
  district_couples_with_children_percentage FLOAT64,
  district_single_parents FLOAT64,
  district_shared_apartments FLOAT64,
  district_only_seniors_households FLOAT64,
  district_apartment_ownes FLOAT64,
  district_apartment_owner_percentage FLOAT64,
  district_apartment_tenants FLOAT64,
  district_apartment_tenant_percentage FLOAT64,
  `2_person_EUR_per_squared_meter` FLOAT64,
  district_apartment_average_rooms FLOAT64,
  `2_person_average_rooms` FLOAT64,
  district_average_persons_per_household FLOAT64,
  district_average_years_of_residence FLOAT64,
  district_full_time_employees FLOAT64,
  district_median_income FLOAT64,
  district_total_population FLOAT64,
  district_male_population FLOAT64,
  district_male_population_percentage FLOAT64,
  district_female_population FLOAT64,
  district_female_population_percentage FLOAT64,
  district_single_population FLOAT64,
  district_couples_population FLOAT64,
  district_widowed_population FLOAT64,
  district_divorced_population FLOAT64,
  district_other_civil_status_population FLOAT64,
  district_average_age FLOAT64,
  district_population_under_18 FLOAT64,
  district_population_under_18_percentage FLOAT64,
  district_population_18_29 FLOAT64,
  district_population_18_29_percentage FLOAT64,
  district_population_30_49 FLOAT64,
  district_population_30_49_percentage FLOAT64,
  district_population_50_64 FLOAT64,
  district_population_50_64_percentage FLOAT64,
  district_population_65_plus FLOAT64,
  district_population_65_plus_percentage FLOAT64,
  district_min_rent_m2 FLOAT64,
  district_avg_rent_m2 FLOAT64,
  district_max_rent_m2 FLOAT64,
  district_min_Buy_m2 FLOAT64,
  district_avg_buy_m2 FLOAT64
);
