-- subdistrict_poi_counts_schema.sql
-- Bronze table: subdistrict_poi_counts
-- Raw counts of POI categories per subdistrict

CREATE TABLE `berlin-housing.bronze.subdistrict_poi_counts` (
  ortsteil STRING,
  alcohol INT64,
  animal_training INT64,
  antiques INT64,
  art INT64,
  bar INT64,
  bathing_place INT64,
  books INT64,
  butcher INT64,
  childcare INT64,
  clothes INT64,
  community_centre INT64,
  confectionery INT64,
  convenience INT64,
  deli INT64,
  dog_park INT64,
  electronics INT64,
  fitness_station INT64,
  florist INT64,
  fountain INT64,
  garden INT64,
  greenfield INT64,
  greengrocer INT64,
  hairdresser INT64,
  ice_cream INT64,
  kiosk INT64,
  marina INT64,
  nature_reserve INT64,
  nightclub INT64,
  parking INT64,
  pitch INT64,
  playground INT64,
  restaurant INT64,
  second_hand INT64,
  stationery INT64,
  supermarket INT64,
  tea INT64,
  art_2 INT64,
  theatre INT64,
  travel_agency INT64,
  vacant INT64,
  wine INT64,
  yes INT64,
  cafes INT64,
  bakeries INT64,
  green_space INT64,
  schools INT64,
  medical STRING
);
